# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
version: "2"
run:
  issues-exit-code: 1
  tests: true
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  enable:
    - copyloopvar
    - dupl
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - lll
    - misspell
    - nolintlint
    - prealloc
    - unconvert
  disable:
    - exhaustive
    - funlen
    - varnamelen
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - unnamedResult
        - hugeParam
      enabled-tags:
        - diagnostic
        - style
        - performance
    gocyclo:
      min-complexity: 20
    govet:
      disable:
        - fieldalignment
      enable-all: true
    lll:
      line-length: 120
    misspell:
      locale: US
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - goconst
          - gosec
        path: _test\.go
      - linters:
          - staticcheck
        path: _test\.go
        text: should not use dot imports
      - linters:
          - staticcheck
        source: \. "github\.com/openfga/go-sdk/client"
    paths:
      - .*_test.go
      - bin
      - vendor
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - .*_test.go
      - bin
      - vendor
      - third_party$
      - builtin$
      - examples$
