# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
# MegaLinter configuration file
# See https://megalinter.io/configuration/

# General settings
APPLY_FIXES: none  # Don't auto-fix files in CI
DEFAULT_BRANCH: main
PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true

# File filters
FILTER_REGEX_EXCLUDE: |
  (\.git/)
  (bin/)
  (coverage\.(out|html))
  (\.claude)

# Enable specific linters
ENABLE_LINTERS:
  - ACTION_ACTIONLINT
  - DOCKERFILE_HADOLINT
  - GO_GOLANGCI_LINT
  - GO_SEC
  - YAML_YAMLLINT
  - MARKDOWN_MARKDOWNLINT
  - SPELL_CSPELL
  - REPOSITORY_CHECKOV
  - REPOSITORY_SECRETLINT
  - REPOSITORY_TRIVY

# Disable problematic linters
DISABLE_LINTERS:
  - COPYPASTE_JSCPD  # Can be too strict for Go code
  - REPOSITORY_GITLEAKS  # Using other secret scanners
  - GO_GOLANGCI_LINT  # Go version mismatch in MegaLinter container

# Go-specific settings
GO_GOLANGCI_LINT_ARGUMENTS: --timeout=5m
GO_SEC_ARGUMENTS: -fmt sarif -out gosec.sarif -quiet

# YAML settings
YAML_YAMLLINT_CONFIG_FILE: .yamllint.yml

# Markdown settings
MARKDOWN_MARKDOWNLINT_CONFIG_FILE: .markdownlint.yml

# Dockerfile settings
DOCKERFILE_HADOLINT_ARGUMENTS: --ignore DL3008 --ignore DL3009

# Spelling
SPELL_CSPELL_CONFIG_FILE: .cspell.json

# Security scanning
REPOSITORY_CHECKOV_ARGUMENTS: --skip-check CKV_DOCKER_2,CKV_DOCKER_3
REPOSITORY_TRIVY_ARGUMENTS: --skip-dirs bin,vendor
