# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
extends: default
ignore: |
  charts/lfx-v2-fga-sync/templates/
rules:
  line-length:
    max: 120
    level: warning
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
  comments:
    min-spaces-from-content: 1
  indentation:
    spaces: 2
    indent-sequences: true
  braces:
    min-spaces-inside: -1
    max-spaces-inside: -1
